CREATE TABLE "ConversionData100" (
	"ConversionName"	TEXT NOT NULL UNIQUE,
	"Caliber"	TEXT NOT NULL,
	"ReserveAmmoCapacity"	INTEGER NOT NULL,
	"MagazineCapacity"	INTEGER NOT NULL,
	"HeadMultiplier"	REAL NOT NULL,
	"TorsoMultiplier"	REAL NOT NULL,
	"LimbMultiplier"	REAL NOT NULL,
	"Damage1"	REAL NOT NULL,
	"Damage2"	REAL NOT NULL,
	"Damage1Range"	REAL NOT NULL,
	"Damage2Range"	REAL NOT NULL,
	"MuzzleVelocity"	REAL NOT NULL,
	"PenetrationDepth"	REAL NOT NULL,
	"Suppression"	REAL NOT NULL,
	"ReloadTime"	INTEGER NOT NULL,
	"EmptyReloadTime"	INTEGER NOT NULL,
	"AimingWalkspeed"	INTEGER NOT NULL,
	"WeaponWalkspeed"	INTEGER NOT NULL,
	"Version"	TEXT,
	"Firemode1"	TEXT NOT NULL,
	"Firemode1Firerate"	REAL NOT NULL,
	"Firemode1Special"	TEXT,
	"Firemode1Pellets"	INTEGER,
	"Firemode2"	TEXT,
	"Firemode2Firerate"	REAL,
	"Firemode2Special"	TEXT,
	"Firemode2Pellets"	INTEGER,
	"Firemode3"	TEXT,
	"Firemode3Firerate"	REAL,
	"Firemode3Special"	TEXT,
	"Firemode3Pellets"	INTEGER,
	PRIMARY KEY("ConversionName")
);

CREATE TABLE "GrenadeData100" (
	"Name"	TEXT NOT NULL UNIQUE,
	"HasRank"	TEXT NOT NULL,
	"Rank"	INTEGER,
	"FuseTime"	REAL,
	"SpecialEffects"	TEXT,
	"BlastRadius"	REAL NOT NULL,
	"KillingRadius"	REAL,
	"MaximumDamage"	REAL NOT NULL,
	"Version"	TEXT,
	"Category"	TEXT NOT NULL,
	"StoredCapacity" INTEGER NOT NULL,
	PRIMARY KEY("Name")
);

CREATE TABLE "GunData100" (
	"DefaultName"	TEXT NOT NULL UNIQUE,
	"HasRank"	TEXT NOT NULL,
	"Rank"	INTEGER,
	"Version"	REAL NOT NULL,
	"Category"	INTEGER NOT NULL,
	"Conversion1"	TEXT,
	"Conversion2"	TEXT,
	"Conversion3"	TEXT,
	"Conversion4"	TEXT,
	"Conversion5"	TEXT,
	"Conversion6"	TEXT,
	"Conversion7"	TEXT,
	"Conversion8"	TEXT,
	"Conversion9"	TEXT,
	"Conversion10"	TEXT,
	PRIMARY KEY("DefaultName"),
	FOREIGN KEY("Conversion10") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion6") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion4") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion2") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion1") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion8") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion3") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion7") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion5") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion9") REFERENCES "ConversionData100"("ConversionName")
);

CREATE TABLE "MeleeData100" (
	"Name"	TEXT NOT NULL UNIQUE,
	"HasRank"	TEXT NOT NULL,
	"Rank"	INTEGER,
	"BladeLength"	REAL NOT NULL,
	"FrontStabDamage"	REAL NOT NULL,
	"BackStabDamage"	REAL NOT NULL,
	"HeadMultiplier"	REAL NOT NULL,
	"TorsoMultiplier"	REAL NOT NULL,
	"LimbMultiplier"	REAL NOT NULL,
	"Walkspeed"	REAL NOT NULL,
	"Version"	TEXT,
	"Category"	TEXT NOT NULL,
	PRIMARY KEY("Name")
);

CREATE TABLE "ConversionData101" (
	"ConversionName"	TEXT NOT NULL UNIQUE,
	"Caliber"	TEXT NOT NULL,
	"ReserveAmmoCapacity"	INTEGER NOT NULL,
	"MagazineCapacity"	INTEGER NOT NULL,
	"HeadMultiplier"	REAL NOT NULL,
	"TorsoMultiplier"	REAL NOT NULL,
	"LimbMultiplier"	REAL NOT NULL,
	"Damage1"	REAL NOT NULL,
	"Damage2"	REAL NOT NULL,
	"Damage1Range"	REAL NOT NULL,
	"Damage2Range"	REAL NOT NULL,
	"MuzzleVelocity"	REAL NOT NULL,
	"PenetrationDepth"	REAL NOT NULL,
	"Suppression"	REAL NOT NULL,
	"ReloadTime"	INTEGER NOT NULL,
	"EmptyReloadTime"	INTEGER NOT NULL,
	"AimingWalkspeed"	INTEGER NOT NULL,
	"WeaponWalkspeed"	INTEGER NOT NULL,
	"Version"	TEXT,
	"Firemode1"	TEXT NOT NULL,
	"Firemode1Firerate"	REAL NOT NULL,
	"Firemode1Special"	TEXT,
	"Firemode1Pellets"	INTEGER,
	"Firemode2"	TEXT,
	"Firemode2Firerate"	REAL,
	"Firemode2Special"	TEXT,
	"Firemode2Pellets"	INTEGER,
	"Firemode3"	TEXT,
	"Firemode3Firerate"	REAL,
	"Firemode3Special"	TEXT,
	"Firemode3Pellets"	INTEGER,
	PRIMARY KEY("ConversionName")
);

CREATE TABLE "GrenadeData101" (
	"Name"	TEXT NOT NULL UNIQUE,
	"HasRank"	TEXT NOT NULL,
	"Rank"	INTEGER,
	"FuseTime"	REAL,
	"SpecialEffects"	TEXT,
	"BlastRadius"	REAL NOT NULL,
	"KillingRadius"	REAL,
	"MaximumDamage"	REAL NOT NULL,
	"Version"	TEXT,
	"Category"	TEXT NOT NULL,
	"StoredCapacity" INTEGER NOT NULL,
	PRIMARY KEY("Name")
);

CREATE TABLE "GunData101" (
	"DefaultName"	TEXT NOT NULL UNIQUE,
	"HasRank"	TEXT NOT NULL,
	"Rank"	INTEGER,
	"Version"	REAL NOT NULL,
	"Category"	INTEGER NOT NULL,
	"Conversion1"	TEXT,
	"Conversion2"	TEXT,
	"Conversion3"	TEXT,
	"Conversion4"	TEXT,
	"Conversion5"	TEXT,
	"Conversion6"	TEXT,
	"Conversion7"	TEXT,
	"Conversion8"	TEXT,
	"Conversion9"	TEXT,
	"Conversion10"	TEXT,
	PRIMARY KEY("DefaultName"),
	FOREIGN KEY("Conversion10") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion6") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion4") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion2") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion1") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion8") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion3") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion7") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion5") REFERENCES "ConversionData100"("ConversionName"),
	FOREIGN KEY("Conversion9") REFERENCES "ConversionData100"("ConversionName")
);

CREATE TABLE "MeleeData101" (
	"Name"	TEXT NOT NULL UNIQUE,
	"HasRank"	TEXT NOT NULL,
	"Rank"	INTEGER,
	"BladeLength"	REAL NOT NULL,
	"FrontStabDamage"	REAL NOT NULL,
	"BackStabDamage"	REAL NOT NULL,
	"HeadMultiplier"	REAL NOT NULL,
	"TorsoMultiplier"	REAL NOT NULL,
	"LimbMultiplier"	REAL NOT NULL,
	"Walkspeed"	REAL NOT NULL,
	"Version"	TEXT,
	"Category"	TEXT NOT NULL,
	PRIMARY KEY("Name")
);